//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupsSecretaries
    {
        public int Id { get; set; }
        public System.DateTime Session_Begin { get; set; }
        public System.DateTime Session_End { get; set; }
        public int SecretarId { get; set; }
        public int GroupId { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Secretaries Secretaries { get; set; }
    }
}
